[build]
  functions = "/netlify/functions/"

[[redirects]]
  from = "/functions/*"
  to = "/api/:splat"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/*.json"
  [headers.values]
    Content-Type = "application/json"

[[headers]]
  for = "/api/*"
  [headers.values]
    Content-Type = "application/json"

[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"